name: Changelog

on:
  workflow_dispatch:
  push:
    tags:
      - 'deploy-*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: sha_short
        run: echo "::set-output name=val::$(git rev-parse --short HEAD)"

      - id: ctr
        if: startsWith(github.ref, 'refs/tags/deploy-singsaver-')
        run: echo "::set-output name=val::Singsaver"

      - name: Find Last Release Tag
        uses: oprypin/find-latest-tag@v1.1.0
        id: baseref
        with:
          repository: ${{ github.repository }}
          prefix: 'deploy-singsaver-'
          releases-only: true
      - name: Log Last Release Tag        
        run: echo '${{ steps.baseref.outputs.tag }}'

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.sha }}
          base-ref: ${{ steps.baseref.outputs.tag }}

      - name: Get the changelog
        run: echo '${{ steps.changelog.outputs.changelog }}' #syntax error near unexpected token `('

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.sha_short.outputs.val }} to ${{ steps.ctr.outputs.val }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      #- name: Send message to Slack API
      #  uses: archive/github-actions-slack@v2.0.0
      #  id: notify
      #  with:
      #    slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
      #    slack-channel: CPPUV5KU0
      #    slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }} ${{ steps.changelog.outputs.changelog }}"
      #- name: Result from "Send Message"
      #  run: echo "The result was ${{ steps.notify.outputs.slack-result }}"