name: Changelog

on:
  workflow_dispatch:
  push:
    tags:
      - 'deploy-singsaver-*'
      - 'deploy-moneyhero-*'
      - 'deploy-money101-*'
      - 'deploy-moneyguru-*'
      - 'deploy-moneymax-*'
      - 'deploy-comparehero-*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: sha_short
        run: echo "::set-output name=val::$(git rev-parse --short HEAD)"

      - id: ctr
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: 'deploy-(.*?)-'

      - name: Find Last Release Tag
        uses: oprypin/find-latest-tag@v1.1.0
        id: baseref
        with:
          repository: ${{ github.repository }}
          prefix: 'deploy-${{ steps.ctr.outputs.group1 }}-'
          releases-only: true
      - name: Log Last Release Tag        
        run: echo '${{ steps.baseref.outputs.tag }}'

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.sha }}
          base-ref: ${{ steps.baseref.outputs.tag }}

      #- name: Get the changelog
      #  run: echo '${{ steps.changelog.outputs.changelog }}' #syntax error near unexpected token `('

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.sha_short.outputs.val }} to ${{ steps.ctr.outputs.group1 }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Escape
        id: foo
        run: |
          printf -v var "%q\n" "${{ steps.changelog.outputs.changelog }}"
          echo "$var"
          echo "::set-output name=val::$var"

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: '{"msg":"hello"}'
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/workflows/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

      #- name: Post to a Slack channel
      #  id: slack
      #  uses: slackapi/slack-github-action@v1.14.0
      #  with:
      #    channel-id: 'C0274KS2L87'  # Slack channel id to post message
      #    slack-message: ${{ steps.changelog.outputs.changelog }}
      #  env:
      #    SLACK_BOT_TOKEN: xoxb-206242252071-2270433947361-TVbgcMb7XenXDBTPigGnLZVQ